### ISSUE TITLE
"Invalid \"Referrer\" header"

### ISSUE THREAD

**Issue by SudoPlz** [formspree/formspree#73]
I don't know what I'm doing wrong, it could be something very basic but right now I totally miss the error.
Thats my javascript code:
```
$.ajax({
	    url: "http://formspree.io/****@gmail.com",  //I'm not showing my real mail address here
	    method: "POST",
	    data: {message: "hello!"},
	    dataType: "json",
	    error: function(xhr, status, error) {
		    console.log("MyResponse: "+xhr.responseText + "MyError: "+error);
		},
	});
```

Then I receive:
```
MyResponse: {
  "error": "Invalid \"Referrer\" header"
} MyError: BAD REQUEST
```

Why do I get this response?
Thank you..!

**Comment by rohitdatta** [comment]
This issue was closed because it does not meet the [contributor guidelines](../blob/master/.github/CONTRIBUTING.md). Please only submit an issue if it is a bug with Formspree itself. Any problems setting up Formspree on your own site should be addressed by emailing [team@formspree.io](mailto:team@formspree.io).

**Comment by luanfonceca** [comment]
@SudoPlz i got this error too, but it happen when you try to send an email from a not hosted site, like in your own pc, the referrer appoints to a url origin, as you are not hosted anywhere you get this error.

**Comment by SudoPlz** [comment]
You are absolutely right @luanfonceca , that was the problem, I forgot to come back and comment on it. Thank you!
