### ISSUE TITLE
Send Text

### ISSUE THREAD

**Issue by herohamp** [formspree/formspree#93]
How can you make it so in the fourm they can send you text? the doc does not show any info!

**Comment by rohitdatta** [comment]
This issue was closed because it does not meet the [contributor guidelines](../blob/master/.github/CONTRIBUTING.md). Please only submit an issue if it is a bug with Formspree itself. Any problems setting up Formspree on your own site should be addressed by emailing [team@formspree.io](mailto:team@formspree.io). We'd be happy to help there!
