### ISSUE TITLE
Configuring confirmed websites

### ISSUE THREAD

**Issue by bahadircyildiz** [formspree/formspree#96]
While I was developing my website, I put a formspree form to my local work and send it for trying. After confirmation, I realized that my official mail is confirmed with http://localhost:4000. I would like to disable my localhost from confirmed ones. IS there a way to do so?

**Comment by rohitdatta** [comment]
This issue was closed because it does not meet the [contributor guidelines](../blob/master/.github/CONTRIBUTING.md). Please only submit an issue if it is a bug with Formspree itself. For security purposes, any problems relating to Formspree on your own site or account issues should be addressed by emailing [team@formspree.io](mailto:team@formspree.io). We'd be happy to help there!
